spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres?currentSchema=postgres&ApplicationName=hikari_test
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect